package com.daoekinc.pinfit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * A file generated by a pre-rebrand version of this tool uses {@code /*@CGen(...)*&#47;} markers
 * throughout - the file marker, every usercode+/- pair, the skeleton hash. Pinfit must read all of
 * that untouched, keep the user's own code exactly as written, and silently upgrade every marker
 * to {@code @Pinfit} the next time the file is regenerated. See PinfitTag/TagHelper.
 */
class TagRebrandMigrationTest {
    @TempDir
    Path temporaryDirectory;

    @Test
    void legacyCGenMarkersAreReadAndSelfUpgradeOnRegenerate() throws Exception {
        CliFixture cli = new CliFixture(temporaryDirectory);
        assertEquals(0, cli.run("init"));
        assertEquals(0, cli.run("create", "interface", "sensor"));
        assertEquals(0, cli.run("create", "module", "sensor_impl", "--implements", "sensor"));
        assertEquals(0, cli.run("generate"));

        Path source = temporaryDirectory.resolve("sensor_impl.c");
        String generated = Files.readString(source);
        assertTrue(generated.contains("/*@Pinfit(file:module-source:"), "sanity: current brand is written first");

        String precious = "    return 42; /* PRECIOUS_USER_CODE */";
        String withUserCode = generated.replace(
                "/*@Pinfit usercode+ function.sensor.init.body*/\n",
                "/*@Pinfit usercode+ function.sensor.init.body*/\n" + precious + "\n");

        // Simulate a file untouched since an old CGen version wrote it: every marker (file,
        // usercode+/-) uses the old brand, and there is no skeleton-hash line yet - that guard
        // was computed over CGen-branded bytes that no longer exist once this test rewrites them,
        // and TagHelper already treats a missing hash as "from before this feature existed",
        // skipped rather than flagged (see TagHelper.requireSkeletonUnchanged).
        String[] lines = withUserCode.split("\n", -1);
        assertTrue(lines[1].contains("skeleton-hash"), "sanity: second line is the skeleton hash");
        String withoutHashLine = lines[0] + "\n" + String.join("\n", java.util.Arrays.asList(lines).subList(2, lines.length));
        String legacyBranded = withoutHashLine.replace("@Pinfit", "@CGen");
        Files.writeString(source, legacyBranded);
        assertTrue(legacyBranded.contains(precious), "test setup sanity check");

        assertEquals(0, cli.run("generate"), cli.errors());

        String regenerated = Files.readString(source);
        assertTrue(regenerated.contains(precious), "user code must survive reading legacy markers");
        assertTrue(regenerated.contains("/*@Pinfit(file:module-source:"), "file marker must self-upgrade to the current brand");
        assertTrue(regenerated.contains("/*@Pinfit usercode+ function.sensor.init.body*/"),
                "usercode markers must self-upgrade to the current brand");
        assertFalse(regenerated.contains("@CGen"), "no legacy marker should remain after a regenerate");
    }
}
