package com.daoekinc.cgen.generate;

import com.daoekinc.cgen.model.ProjectConfig;
import com.daoekinc.cgen.model.StateMachineSpec;
import com.daoekinc.cgen.model.StateMachineSpec.State;
import com.daoekinc.cgen.model.StateMachineSpec.Transition;
import com.daoekinc.cgen.tag.CGenTag;

/**
 * Emits {@code <name>_sm/<name>_sm.plantuml} - CGen-owned input, StateSmith-consumed, never
 * hand-edited. Every action and guard it emits is a call into the hooks module
 * ({@link StateSmithHooksRenderer}); no user logic ever lives in this file.
 */
final class StateSmithPlantUmlRenderer {
    String render(ProjectConfig project, StateMachineSpec machine) {
        String smName = StateSmithNaming.smIdentifier(machine.name());
        StringBuilder out = new StringBuilder();

        // PlantUML has no /* */ syntax; a leading "'" makes this a plain line comment, and
        // CGenTag's marker regex tolerates that prefix so the file is still refused-to-overwrite
        // like any other CGen-owned file. Confirmed with a real ss.cli run that a comment line
        // before @startuml does not break parsing.
        out.append("' ").append(CGenTag.generatedFile("state-machine-plantuml", machine.source().getFileName().toString())).append('\n');
        out.append('\n');
        out.append("@startuml ").append(smName).append('\n');
        out.append('\n');
        appendConfig(out, machine, smName);
        out.append('\n');
        for (State state : machine.states()) {
            appendStateDeclaration(out, state, 0);
        }
        out.append('\n');
        out.append("[*] --> ").append(machine.initial()).append('\n');
        out.append('\n');
        for (Transition transition : machine.transitions()) {
            appendTransition(out, project, machine, transition);
        }
        out.append('\n');
        for (State state : machine.allStatesFlat()) {
            appendBehavior(out, project, machine, state);
        }
        out.append('\n');
        out.append("@enduml\n");
        return out.toString();
    }

    private static void appendStateDeclaration(StringBuilder out, State state, int depth) {
        String indent = "  ".repeat(depth);
        if (state.isComposite()) {
            out.append(indent).append("state ").append(state.name()).append(" {\n");
            if (state.initial() != null) {
                out.append(indent).append("  [*] --> ").append(state.initial()).append('\n');
            }
            for (State child : state.states()) {
                appendStateDeclaration(out, child, depth + 1);
            }
            out.append(indent).append("}\n");
        } else {
            out.append(indent).append("state ").append(state.name()).append('\n');
        }
    }

    private static void appendTransition(StringBuilder out, ProjectConfig project, StateMachineSpec machine, Transition transition) {
        boolean isTick = transition.event().equals(StateMachineSpec.TICK_EVENT);
        String eventLabel = isTick ? "do" : transition.event();
        out.append(transition.from()).append(" --> ").append(transition.to()).append(" : ").append(eventLabel);
        if (transition.guard()) {
            out.append(" [").append(call(HookNames.transitionGuard(project, machine, transition))).append(']');
        }
        out.append(" / ").append(call(HookNames.transitionAction(project, machine, transition))).append(";\n");
    }

    private static void appendBehavior(StringBuilder out, ProjectConfig project, StateMachineSpec machine, State state) {
        out.append(state.name()).append(" : enter / ").append(call(HookNames.stateEntry(project, machine, state.name()))).append(";\n");
        out.append(state.name()).append(" : exit / ").append(call(HookNames.stateExit(project, machine, state.name()))).append(";\n");
        out.append(state.name()).append(" : do / ").append(call(HookNames.stateTick(project, machine, state.name()))).append(";\n");
    }

    private static String call(String functionName) {
        return functionName + "(sm->vars.context)";
    }

    private static void appendConfig(StringBuilder out, StateMachineSpec machine, String smName) {
        String yamlFileName = machine.source().getFileName().toString();
        String hooksHeader = StateSmithNaming.hooksHeaderFileName(machine.name());
        out.append("/'! $CONFIG : toml\n\n");
        out.append("[SmRunnerSettings]\n");
        out.append("transpilerId = \"C99\"\n\n");
        out.append("[RenderConfig]\n");
        out.append("FileTop = \"\"\"\n");
        out.append(CGenTag.generatedFile("state-machine-statesmith", yamlFileName)).append('\n');
        out.append("/* Generated by StateSmith via CGen from ").append(yamlFileName).append(" - do not edit. */\n");
        out.append("\"\"\"\n");
        out.append("VariableDeclarations = \"\"\"\n");
        out.append(machine.name()).append("_context_t *context;\n");
        out.append("\"\"\"\n\n");
        out.append("[RenderConfig.C]\n");
        out.append("HFileTop = \"\"\"\n");
        out.append("typedef struct ").append(machine.name()).append("_context_t ").append(machine.name()).append("_context_t;\n");
        out.append("\"\"\"\n");
        out.append("CFileIncludes = \"\"\"\n");
        out.append("#include \"../").append(hooksHeader).append("\"\n");
        out.append("\"\"\"\n");
        out.append("'/\n");
    }
}
